# Generated by Django 4.0.4 on 2022-05-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0002_rename_autor_blogposts_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogposts',
            options={'ordering': ('-post_created_on',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='slug',
            field=models.SlugField(max_length=350, null=True, unique=True),
        ),
    ]
