# Generated by Django 4.0.4 on 2022-05-18 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0003_alter_blogposts_options_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='body',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='category',
            field=models.ForeignKey(db_column='category_category', on_delete=django.db.models.deletion.CASCADE, to='blog_post.categories'),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='thumbnail',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to='post_images/%Y/%m/%d/', width_field=250),
        ),
    ]
