# Generated by Django 4.0.4 on 2022-05-18 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0004_alter_blogposts_body_alter_blogposts_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_post.categories'),
        ),
    ]
