# Generated by Django 4.0.4 on 2022-05-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0005_alter_blogposts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='slug',
            field=models.SlugField(blank=True, max_length=350, null=True, unique=True),
        ),
    ]
